### PR TITLE
Update of the BITalino sensors transfer functions (according to PLUX datasheets)

### PR DESCRIPTION
**Pull request by GRamosPlux**
Dear @pires,
I truly hope that this message finds you well and facing exciting challenges in your projects!

During a support task involving the **PLUX Support Team** and a customer using this SDK, it was noticed that some sensor transfer functions were outdated.

Due to this circumstance, we decided to create this pull request (containing the updated transfer functions and unit tests) hoping that it can help the current and future members of your community!

My best and sincere regards,
GRamosPlux

### CODE REVIEW

**Comment by pires** [comment]
Why was this closed only to be re-opened in #7? The commit hashes seem to be the same.

**Comment by GRamosPlux** [comment]
Dear @pires,

I apologize for the mistake, you are totally correct, it was an unnecessary action.
This was the first time that I made a commit after the **Pull Request** and I thought that it wouldn't be included in #6 ':-D

**My best and sincere regards,**
@GRamosPlux

**Comment by pires** [comment]
Totally fine, just wanted to understand. Thanks for clarifying.

**Comment by GRamosPlux** [comment]
Dear @pires,

Thank you very much for your comprehension ;-)
Despite the undesirable mistake, this situation was really instructive to avoid similar actions in the future!

**My best and sincere regards,**
@GRamosPlux

**Pull request closed without merging**
